import { BN } from "bn.js";

export const VDXF_OBJECT_RESERVED_BYTE_I_ADDR = new BN(102, 10);
export const VDXF_OBJECT_RESERVED_BYTE_VDXF_ID_STRING = new BN(103, 10);
export const VDXF_OBJECT_RESERVED_BYTE_ID_OR_CURRENCY = new BN(104, 10);
export const VDXF_ORDINAL_DATA_DESCRIPTOR = new BN(0, 10);
export const VDXF_ORDINAL_VERUSPAY_INVOICE = new BN(1, 10);
export const VDXF_ORDINAL_IDENTITY_UPDATE_REQUEST = new BN(3, 10);
export const VDXF_ORDINAL_IDENTITY_UPDATE_RESPONSE = new BN(4, 10);